getwd()
list.files()
data<- read.table('household_power_consumption.txt', header = T, sep=';')
datetime<- paste(data$Date, data$Time)
head(datetime)
datetime<- as.POSIXct(datetime, format= '%d/%m/%Y %H:%M:%S')
data$datetime<- datetime
names(data)
data<- data[data$Date=='1/2/2007' | data$Date=='2/2/2007',]
par(mar=c(1,4,1,2.5))
par(mfrow=c(2,2))
plot(data$datetime, as.numeric(data$Global_active_power)/500,ylab='Global Active Power', type='l')
plot(data$datetime, as.numeric(data$Voltage), type='l', ylab='Voltage')
plot(x=data$datetime, y=data$Sub_metering_1, type='l', ylab = 'Submetering')
lines(x=data$datetime, y=data$Sub_metering_2, col='Red')
lines(x=data$datetime, y=data$Sub_metering_3,  col= 'blue')
legend('topright', pch='____', col=c('black','red','blue'), legend = c('Sub_metering_1','Sub_metering_2','Sub_metering_3'))
plot(data$datetime, as.numeric(data$Global_reactive_power)/500, type='l', ylab= "Global Reactive power")
dev.copy(png, "plot4.png")
dev.off()
